syn match agdaInfixFunction "\<\*\>\|\<+\>\|\<-\>\|\<<\>\|\<≡\>"
syn match agdaInfixFunction "\<==\>"
syn match agdaConstructor "\<suc\>"
syn match agdaFunction "\<_\*_\>\|\<_+_\>\|\<_-_\>\|\<_<_\>\|\<_≡_\>\|\<Nat\>\|\<Set\>\|\<n+0\>"
syn match agdaConstructor "\<refl\>\|\<zero\>"
syn match agdaFunction "\<_==_\>"
syn match agdaFunction "\<div-helper\>\|\<mod-helper\>"
syn match agdaFunction "\<primRewriteNoMatch\>"
