name: Build (stack)

on:
  push: &trigger_paths
    branches: [ "main", "ci-*", "release*" ]
    paths: &trigger_path_list
    - '.github/workflows/stack.yml'
    - 'dype.cabal'
    - 'config/stack-*.yaml'
    - 'src/**'

  pull_request:
    paths: *trigger_path_list

  workflow_dispatch:

jobs:
  auto-cancel:
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
      && !contains(github.event.head_commit.message, '[ci skip]')
      && !contains(github.event.head_commit.message, '[github skip]')
      && !contains(github.event.head_commit.message, '[skip github]')
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.13.1
      with:
        access_token: ${{ github.token }}

  stack: &stack_job
    needs: auto-cancel
    timeout-minutes: 60

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        ghc-ver: [9.14.1, 9.12.4, 9.10.3, 9.8.4, 9.6.7, 9.4.8, 9.2.8]
        include:
        - os: macos-15
          ghc-ver: 9.14.1
        - os: windows-2025
          ghc-ver: 9.14.1

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v7

    - uses: clearnature/setup@main
      id: haskell-setup
      with:
        ghc-version: ${{ matrix.ghc-ver }}
        stack-version: '3.11.1'
        enable-stack: true
        cabal-update: false

    - name: Environment settings
      run: |
        echo "runner.os         = ${{ runner.os                               }}"
        echo "ghc-path          = ${{ steps.haskell-setup.outputs.ghc-path    }}"
        echo "cabal-path        = ${{ steps.haskell-setup.outputs.cabal-path  }}"
        echo "stack-root        = ${{ steps.haskell-setup.outputs.stack-root  }}"
        echo "STACK_ROOT=${{ steps.haskell-setup.outputs.stack-root }}" >> "${GITHUB_ENV}"
        echo "STACK_VER=$(stack --numeric-version)"                     >> "${GITHUB_ENV}"
        GHC_VER=$(ghc --numeric-version)
        echo "GHC_VER=${GHC_VER}"                                       >> "${GITHUB_ENV}"
        echo "ARGS=--stack-yaml=${GITHUB_WORKSPACE}/config/stack-${GHC_VER}.yaml --system-ghc --no-terminal"    >> "${GITHUB_ENV}"
        # Default ICU version (overwritten on macOS/Windows)
        echo "ICU_VER=0"                                                >> "${GITHUB_ENV}"

    - name: Restore cache
      uses: actions/cache/restore@v6
      id:   cache
      env:
        key: stack-${{ runner.os }}-ghc-${{ env.GHC_VER }}-stack-${{ env.STACK_VER }}-icu-${{ env.ICU_VER }}
      with:
        key: ${{ env.key }}-plan-${{ hashFiles('dype.cabal', format('config/stack-{0}.yaml', env.GHC_VER)) }}
        restore-keys: ${{ env.key }}-
        path: ${{ env.STACK_ROOT }}

    - name: Install the ICU library (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install icu4c
        ICU4C=$(brew --prefix)/opt/icu4c
        echo "PKG_CONFIG_PATH=${ICU4C}/lib/pkgconfig" >> "${GITHUB_ENV}"

    - name: Install the ICU library (Windows)
      if: runner.os == 'Windows'
      run: |
        # shellcheck disable=SC2086
        stack exec ${ARGS} -- pacman --noconfirm -S mingw-w64-x86_64-icu mingw-w64-x86_64-pkgconf mingw-w64-x86_64-zlib

    - name: Determine the ICU version
      run: |
        # shellcheck disable=SC2086
        ICU_VER=$(stack exec ${ARGS} -- pkg-config --modversion icu-i18n)
        echo "ICU_VER=${ICU_VER}"
        echo "ICU_VER=${ICU_VER}" >> "${GITHUB_ENV}"

    - name: Install dependencies
      run: |
        # shellcheck disable=SC2086
        stack build ${ARGS} --test --bench --only-dependencies

    - name: Build
      run: |
        # shellcheck disable=SC2086
        stack build ${ARGS} --test --bench --no-run-tests

    - name: Run tests
      run: |
        # shellcheck disable=SC2086
        stack test ${ARGS}

    - name: Run benchmarks
      run: |
        # shellcheck disable=SC2086
        stack bench ${ARGS}

    - name: Save cache
      uses: actions/cache/save@v6
      if:   always() && steps.cache.outputs.cache-matched-key != steps.cache.outputs.cache-primary-key
      with:
        key:  ${{ steps.cache.outputs.cache-primary-key }}
        path: ${{ env.STACK_ROOT }}
