name: Whitespace

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
    - main
    - ci-*
    - release*
  pull_request:

jobs:
  check:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - uses: andreasabel/fix-whitespace-action@v1
