cradle:
  stack:
    - path: './src'
      component: 'dype:lib'
    - path: './vendor/agda-src'
      component: 'agda-syntax:lib'
    - path: './vendor/agda-syntax/src'
      component: 'agda-syntax:lib'
    - path: './app'
      component: 'dype:exe:gen-demo'
    - path: './test'
      component: 'dype:test:dype-test'
    - path: './bench'
      component: 'dype:bench:dype-bench'
