cradle:
  stack:
    - path: './src'
      component: 'dype-core:lib'
    - path: './app'
      component: 'dype:exe:gen-demo'
    - path: './test'
      component: 'dype:test:dype-test'
    - path: './bench'
      component: 'dype:bench:dype-bench'
