syn match agdaInfixFunction "\<if\>"
syn match agdaFunction "\<Set\>\|\<not\>"
syn match agdaConstructor "\<true\>"
syn match agdaFunction "\<Bool\>"
syn match agdaInfixFunction "\<then\>\|\<else\>"
syn match agdaConstructor "\<false\>"
syn match agdaFunction "\<notnot\>"
syn match agdaFunction "\<if_then_else_\>"
