syn match agdaInfixFunction "\<⊔\>"
syn match agdaFunction "\<_⊔_\>\|\<Set\>"
syn match agdaConstructor "\<lift\>"
syn match agdaFunction "\<Lift\>\|\<lsuc\>"
syn match agdaFunction "\<Level\>\|\<lzero\>"
syn match agdaConstructor "\<squash\>"
syn match agdaFunction "\<Squash\>"
syn match agdaFunction "\<LevelUniv\>"
