cabal-version: 2.4
name:          syntax
version:       0.1.0.0
synopsis:      Agda.Syntax parser modules vendored for dype
build-type:    Simple
license:       MIT

library
  default-language: Haskell2010
  hs-source-dirs:   ../full, ../setup, src

  default-extensions:
      BangPatterns
      BlockArguments
      ConstraintKinds
      DefaultSignatures
      DeriveFoldable
      DeriveFunctor
      DeriveGeneric
      DeriveTraversable
      DerivingStrategies
      DerivingVia
      DisambiguateRecordFields
      ExistentialQuantification
      FlexibleContexts
      FlexibleInstances
      FunctionalDependencies
      GADTs
      GeneralizedNewtypeDeriving
      InstanceSigs
      LambdaCase
      MultiParamTypeClasses
      MultiWayIf
      NamedFieldPuns
      OverloadedStrings
      PatternSynonyms
      RankNTypes
      ScopedTypeVariables
      StandaloneDeriving
      TupleSections
      TypeFamilies
      TypeOperators
      TypeSynonymInstances
      ViewPatterns
      TypeApplications
      ImportQualifiedPost

  ghc-options:
      -Wno-name-shadowing
      -Wno-unused-matches
      -Wno-orphans
      -Wno-unused-top-binds
    -Wall -fno-warn-unused-imports -fno-warn-missing-signatures
    -Wno-error=deprecated-flags -Wno-error=tabs

  exposed-modules:
    Agda.Syntax.Parser
    Agda.Syntax.Parser.Monad
    Agda.Syntax.Concrete
    Agda.Syntax.Common
    Agda.Syntax.Common.Pretty
    Agda.Syntax.Position
    Agda.Utils.FileName

  other-modules:
    Agda.Setup
    Agda.Setup.EmacsMode
    Agda.Version
    GHC.Num.WordArray
    Agda.Benchmarking
    Agda.Interaction.Library
    Agda.Interaction.Library.Base
    Agda.Interaction.Library.Parse
    Agda.Interaction.Options
    Agda.Interaction.Options.Arguments
    Agda.Interaction.Options.Base
    Agda.Interaction.Options.Default
    Agda.Interaction.Options.Errors
    Agda.Interaction.Options.HasOptions
    Agda.Interaction.Options.Help
    Agda.Interaction.Options.ProfileOptions
    Agda.Interaction.Options.Types
    Agda.Interaction.Options.Warnings
    Agda.Syntax.Abstract.Name
    Agda.Syntax.Builtin
    Agda.Syntax.Common.Aspect
    Agda.Syntax.Common.KeywordRange
    Agda.Syntax.Concrete.Attribute
    Agda.Syntax.Concrete.Fixity
    Agda.Syntax.Concrete.Glyph
    Agda.Syntax.Concrete.Name
    Agda.Syntax.Concrete.Pattern
    Agda.Syntax.Concrete.Pretty
    Agda.Syntax.Fixity
    Agda.Syntax.Info
    Agda.Syntax.Internal
    Agda.Syntax.Internal.Blockers
    Agda.Syntax.Internal.Elim
    Agda.Syntax.Internal.Univ
    Agda.Syntax.Literal
    Agda.Syntax.Notation
    Agda.Syntax.Parser.Alex
    Agda.Syntax.Parser.Comments
    Agda.Syntax.Parser.Helpers
    Agda.Syntax.Parser.Layout
    Agda.Syntax.Parser.LexActions
    Agda.Syntax.Parser.Lexer
    Agda.Syntax.Parser.Literate
    Agda.Syntax.Parser.LookAhead
    Agda.Syntax.Parser.Parser
    Agda.Syntax.Parser.StringLiterals
    Agda.Syntax.Parser.Tokens
    Agda.Syntax.Scope.Base
    Agda.Syntax.TopLevelModuleName
    Agda.Syntax.TopLevelModuleName.Boot
    Agda.Termination.CutOff
    Agda.TypeChecking.Monad.Base.Types
    Agda.TypeChecking.Positivity.Occurrence
    Agda.Utils.AffineHole
    Agda.Utils.Applicative
    Agda.Utils.AssocList
    Agda.Utils.Bag
    Agda.Utils.Benchmark
    Agda.Utils.BiMap
    Agda.Utils.Boolean
    Agda.Utils.ByteArray
    Agda.Utils.CallStack
    Agda.Utils.CallStack.Base
    Agda.Utils.CallStack.Pretty
    Agda.Utils.CompactRegion
    Agda.Utils.DocTree
    Agda.Utils.Either
    Agda.Utils.Empty
    Agda.Utils.Environment
    Agda.Utils.ExpandCase
    Agda.Utils.FileId
    Agda.Utils.Float
    Agda.Utils.Function
    Agda.Utils.Functor
    Agda.Utils.GetOpt
    Agda.Utils.Hash
    Agda.Utils.IO
    Agda.Utils.IO.UTF8
    Agda.Utils.IORef.Strict
    Agda.Utils.Impossible
    Agda.Utils.Lens
    Agda.Utils.List
    Agda.Utils.List1
    Agda.Utils.List2
    Agda.Utils.ListInf
    Agda.Utils.ListT
    Agda.Utils.Map
    Agda.Utils.Map1
    Agda.Utils.Maybe
    Agda.Utils.Maybe.Strict
    Agda.Utils.MinimalArray.Lifted
    Agda.Utils.Monad
    Agda.Utils.Monoid
    Agda.Utils.Null
    Agda.Utils.POMonoid
    Agda.Utils.PartialOrd
    Agda.Utils.Permutation
    Agda.Utils.Range
    Agda.Utils.RangeMap
    Agda.Utils.SemiRing
    Agda.Utils.Serialize
    Agda.Utils.Set
    Agda.Utils.Set1
    Agda.Utils.Singleton
    Agda.Utils.Size
    Agda.Utils.SmallSet
    Agda.Utils.StrictReader
    Agda.Utils.StrictState
    Agda.Utils.StrictState2
    Agda.Utils.StrictWriter
    Agda.Utils.String
    Agda.Utils.Suffix
    Agda.Utils.Time
    Agda.Utils.Trie
    Agda.Utils.Tuple
    Agda.Utils.Tuple.Strict
    Agda.Utils.TypeLevel
    Agda.Utils.TypeLits
    Agda.Utils.Unsafe
    Agda.Utils.Update
    Agda.Utils.VarSet
    Agda.Utils.WithDefault
    Agda.Utils.Word
    Agda.Utils.Zip

  build-depends:
    base >=4.17 && <5,
    aeson,
    array,
    async,
    bytestring,
    containers,
    data-hash,
    deepseq,
    directory,
    dlist,
    edit-distance,
    enummapset,
    equivalence,
    exceptions,
    filepath,
    ghc-internal,
    ghc-prim,
    hashable,
    monad-control,
    mtl,
    peano,
    pretty,
    process,
    split,
    strict,
    template-haskell,
    text,
    time,
    transformers,
    unordered-containers,
    vector,
    vector-hashtables,
    infinite-list,
    monad-control,
    murmur-hash,
    nonempty-containers,
    primitive,
    boxes,
    generic-data,
    regex-tdfa,
